const PLAID_TO_APP_CATEGORY: Record<string, string> = {
  'FOOD_AND_DRINK': 'FOOD_AND_DRINK',
  'FOOD_AND_DRINK_RESTAURANTS': 'FOOD_AND_DRINK',
  'FOOD_AND_DRINK_COFFEE': 'FOOD_AND_DRINK',
  'FOOD_AND_DRINK_GROCERIES': 'FOOD_AND_DRINK',
  'TRANSPORTATION': 'TRANSPORTATION',
  'TRANSPORTATION_GAS': 'TRANSPORTATION',
  'TRANSPORTATION_PARKING': 'TRANSPORTATION',
  'TRANSPORTATION_PUBLIC_TRANSIT': 'TRANSPORTATION',
  'TRANSPORTATION_RIDE_SHARE': 'TRANSPORTATION',
  'RENT_AND_UTILITIES': 'RENT_AND_UTILITIES',
  'RENT_AND_UTILITIES_RENT': 'RENT_AND_UTILITIES',
  'RENT_AND_UTILITIES_ELECTRIC': 'RENT_AND_UTILITIES',
  'RENT_AND_UTILITIES_INTERNET': 'RENT_AND_UTILITIES',
  'ENTERTAINMENT': 'ENTERTAINMENT',
  'ENTERTAINMENT_MUSIC': 'ENTERTAINMENT',
  'ENTERTAINMENT_GAMES': 'ENTERTAINMENT',
  'ENTERTAINMENT_TV': 'ENTERTAINMENT',
  'GENERAL_MERCHANDISE': 'SHOPPING',
  'PERSONAL_CARE': 'PERSONAL_CARE',
  'MEDICAL': 'HEALTH_AND_FITNESS',
  'EDUCATION': 'EDUCATION',
  'TRAVEL': 'TRAVEL',
  'LOAN_PAYMENTS': 'OTHER',
  'TRANSFER_OUT': 'TRANSFER',
  'TRANSFER_IN': 'TRANSFER',
};

export function mapPlaidCategory(plaidCategory: string): string {
  return PLAID_TO_APP_CATEGORY[plaidCategory] || 'OTHER';
}
